### PR TITLE
Process agones controller metrics as well

### PR DESCRIPTION
**Pull request by luna-duclos**
This PR adds support for scraping metrics off the agones controller used for controlling gameserver fleets. 
This allows us further visibility into our cluster

### CODE REVIEW

**Comment by luna-duclos** [comment]
The docs for the metrics exposed by agones can be found at https://agones.dev/site/docs/guides/metrics/

**Comment by nathanleclaire** [comment]
Hi @luna-duclos ! Thanks for the PR.

I'd be hesitant to add support for Agones metrics directly because it's so specific but here's what I'd propose as a solution instead to help you out - 

1. Make the regex there a configurable value that can be set by the user as a flag for `prom2hny` instead of a compile time one
2. Generate the metric group name automatically from the split instead of having two static ones we choose from

What do you think?

**Comment by luna-duclos** [comment]
Hey @nathanleclaire!

I'm not too sure on 2. It'd be a breaking change compared to right now, as a whole bunch of metric names would change compared to right now (both in the default k8s as well as my own aognes stuff). so it's not very attractive of an option because of that.
I've sadly no alternative suggestions beyond leaving it hard coded as it is now.

**Comment by nathanleclaire** [comment]
@luna-duclos To be clear, what I propose is not changing the metric names in Prometheus. Instead, what I suggest changing is that `switch` block that generates the `metricGroupName` (which I haven't double checked but I'm assuming gets `AddField`-ed to a Honeycomb event somewhere) to something generic that would work for any prefix.

Then we would add something like a multistring flag field to configure which prefixes should be used to match the metrics to get (instead of just `kube`) and always use the generalized form of that procedure for the _Honeycomb_ data. The default would be `--metric-prefix kube`, you would use `--metric-prefix kube --metric-prefix agones` and so on, and other teams would be able to send their own custom metrics using that flag as well.

Would that work for you?

**Comment by luna-duclos** [comment]
Yes, I realize what you're explaining, but I don't think that'd end up with the same names in honeycomb as right now. The reason its currently conditional is because we don't warp all metrics starting with kube, nor does my code change all metrics starting with agones, you'd need to pass in a json files with which metric names to match to do this correctly. Though, I guess a json file could be an option ?

**Comment by nathanleclaire** [comment]
Maybe - I think need to back up a second and understand the format of your current metrics, as well as the goal here. Sorry if I jumped the gun on proposed solutions there.

I assumed you have a metric called `agones_fleet_autoscalers` and the goal is to get that into a Honeycomb event with a field whose value is set to `fleet-autoscalers`. Is that correct or am I off base?

**Comment by luna-duclos** [comment]
Thats mostly correct, for both the kube and agones metrics, it figures out which metrics actually belong to a sub group and then makes those subgroups, this keeps things that belong together nicely grouped.
All metrics are in the same format, but not all metrics with the same prefix belong to the same group, hence the manual coding to get them to work nicely.

**Comment by nathanleclaire** [comment]
Hi @luna-duclos , I'd like to help you out on this one but don't want to introduce any `agones` specific code into prom2hny. Do you have any ideas how we can support this in a general way?

**Comment by MikeGoldsmith** [comment]
We’re going to close this for now. Feel free to re-open, if it’s still relevant.

**Pull request closed without merging**
